//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flee.ElementNames", typeof(ElementNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndOrElement.
        /// </summary>
        public static string AndOrElement {
            get {
                return ResourceManager.GetString("AndOrElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArithmeticElement.
        /// </summary>
        public static string ArithmeticElement {
            get {
                return ResourceManager.GetString("ArithmeticElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BooleanLiteralElement.
        /// </summary>
        public static string BooleanLiteralElement {
            get {
                return ResourceManager.GetString("BooleanLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcEngineAtom.
        /// </summary>
        public static string CalcEngineAtom {
            get {
                return ResourceManager.GetString("CalcEngineAtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastElement.
        /// </summary>
        public static string CastElement {
            get {
                return ResourceManager.GetString("CastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharLiteralElement.
        /// </summary>
        public static string CharLiteralElement {
            get {
                return ResourceManager.GetString("CharLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareElement.
        /// </summary>
        public static string CompareElement {
            get {
                return ResourceManager.GetString("CompareElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionalElement.
        /// </summary>
        public static string ConditionalElement {
            get {
                return ResourceManager.GetString("ConditionalElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeLiteralElement.
        /// </summary>
        public static string DateTimeLiteralElement {
            get {
                return ResourceManager.GetString("DateTimeLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecimalLiteralElement.
        /// </summary>
        public static string DecimalLiteralElement {
            get {
                return ResourceManager.GetString("DecimalLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleLiteralElement.
        /// </summary>
        public static string DoubleLiteralElement {
            get {
                return ResourceManager.GetString("DoubleLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpressionMemberElement.
        /// </summary>
        public static string ExpressionMemberElement {
            get {
                return ResourceManager.GetString("ExpressionMemberElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionCallElement.
        /// </summary>
        public static string FunctionCallElement {
            get {
                return ResourceManager.GetString("FunctionCallElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentifierElement.
        /// </summary>
        public static string IdentifierElement {
            get {
                return ResourceManager.GetString("IdentifierElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexerElement.
        /// </summary>
        public static string IndexerElement {
            get {
                return ResourceManager.GetString("IndexerElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InElement.
        /// </summary>
        public static string InElement {
            get {
                return ResourceManager.GetString("InElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32LiteralElement.
        /// </summary>
        public static string Int32LiteralElement {
            get {
                return ResourceManager.GetString("Int32LiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int64LiteralElement.
        /// </summary>
        public static string Int64LiteralElement {
            get {
                return ResourceManager.GetString("Int64LiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvocationListElement.
        /// </summary>
        public static string InvocationListElement {
            get {
                return ResourceManager.GetString("InvocationListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalBasedElement.
        /// </summary>
        public static string LocalBasedElement {
            get {
                return ResourceManager.GetString("LocalBasedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NegateElement.
        /// </summary>
        public static string NegateElement {
            get {
                return ResourceManager.GetString("NegateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotElement.
        /// </summary>
        public static string NotElement {
            get {
                return ResourceManager.GetString("NotElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullLiteralElement.
        /// </summary>
        public static string NullLiteralElement {
            get {
                return ResourceManager.GetString("NullLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootExpressionElement.
        /// </summary>
        public static string RootExpressionElement {
            get {
                return ResourceManager.GetString("RootExpressionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftElement.
        /// </summary>
        public static string ShiftElement {
            get {
                return ResourceManager.GetString("ShiftElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleLiteralElement.
        /// </summary>
        public static string SingleLiteralElement {
            get {
                return ResourceManager.GetString("SingleLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringLiteralElement.
        /// </summary>
        public static string StringLiteralElement {
            get {
                return ResourceManager.GetString("StringLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpanLiteralElement.
        /// </summary>
        public static string TimeSpanLiteralElement {
            get {
                return ResourceManager.GetString("TimeSpanLiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt32LiteralElement.
        /// </summary>
        public static string UInt32LiteralElement {
            get {
                return ResourceManager.GetString("UInt32LiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt64LiteralElement.
        /// </summary>
        public static string UInt64LiteralElement {
            get {
                return ResourceManager.GetString("UInt64LiteralElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XorElement.
        /// </summary>
        public static string XorElement {
            get {
                return ResourceManager.GetString("XorElement", resourceCulture);
            }
        }
    }
}
